application: octahedronblog
version: version1-4b
runtime: python
api_version: 1

handlers:

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /robots.txt
  static_files: robots.txt 
  upload: robots.tx

- url: /help/bbcode
  static_files: bbcode_help.html 
  upload: bbcode_help.html

- url: /tasks/.*
  script: tasks.py
  login: admin

- url: /stats/.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: .*
  script: main.py

admin_console:
  pages:
  - name: AppStats
    url: /stats/
  - name: Memcache
    url: /admin/memcache

builtins:
- datastore_admin: on
- appstats: on

